require('dotenv').config();

const crypto = require('crypto');
const path = require('path');
const express = require('express');
const cookieParser = require('cookie-parser');
const { createClient } = require('@supabase/supabase-js');

const app = express();
const port = Number(process.env.PORT || 3001);
const frontendOrigin =
  process.env.FRONTEND_ORIGIN || 'http://localhost:3000';

const required = [
  'SUPABASE_URL',
  'SUPABASE_SERVICE_ROLE_KEY'
];

const missing = required.filter(
  (key) => !process.env[key]
);

if (missing.length) {
  console.warn(
    `Missing environment variables: ${missing.join(', ')}`
  );
}

const supabase =
  process.env.SUPABASE_URL &&
  process.env.SUPABASE_SERVICE_ROLE_KEY
    ? createClient(
        process.env.SUPABASE_URL,
        process.env.SUPABASE_SERVICE_ROLE_KEY,
        {
          auth: {
            autoRefreshToken: false,
            persistSession: false
          }
        }
      )
    : null;

/*
 * instant_clients schema (after migration):
 *
 * id                UUID  (generated by Supabase)
 * client_name       text
 * agent_id          text   ← was bigint; see migration.sql
 * from_number_id    text   ← was bigint; see migration.sql
 * source            text
 * integration_token text
 * is_active         boolean
 * created_at        timestamptz
 * updated_at        timestamptz
 */

const column = {
  id:               'id',
  name:             'client_name',
  agent:            'agent_id',
  fromNumber:       'from_number_id',
  source:           'source',
  integrationToken: 'integration_token',
  isActive:         'is_active'
};

app.use(express.json({ limit: '32kb' }));
app.use(cookieParser());

app.use((req, res, next) => {
  res.header('Access-Control-Allow-Origin', frontendOrigin);
  res.header('Vary', 'Origin');
  res.header('Access-Control-Allow-Credentials', 'true');
  res.header('Access-Control-Allow-Headers', 'Content-Type');
  res.header('Access-Control-Allow-Methods', 'GET,POST,PUT,DELETE,OPTIONS');

  if (req.method === 'OPTIONS') return res.sendStatus(204);
  next();
});

const sessions = new Map();
const SESSION_TTL_MS = 8 * 60 * 60 * 1000;

function hash(value) {
  return crypto.createHash('sha256').update(String(value)).digest('hex');
}

function requireConfig(res) {
  if (!supabase) {
    res.status(500).json({ success: false, error: 'Supabase server configuration is missing.' });
    return false;
  }
  return true;
}

function requireAuth(req, res, next) {
  const token = req.cookies.voxora_session;
  const session = token && sessions.get(token);
  if (!session || session.expiresAt <= Date.now()) {
    if (token) sessions.delete(token);
    return res.status(401).json({ success: false, error: 'Authentication required.' });
  }
  next();
}

function isValidUUID(value) {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
}

/* =========================================================
   HEALTH
========================================================= */

app.get('/api/health', (req, res) => {
  res.json({ success: true, service: 'voxora-instant-leads-api' });
});

/* =========================================================
   LOGIN
========================================================= */

app.post('/api/auth/login', (req, res) => {
  const email    = String(req.body?.email || '').trim();
  const password = String(req.body?.password || '');

  const configuredEmail    = process.env.ADMIN_EMAIL || '';
  const configuredPassword = process.env.ADMIN_PASSWORD || '';

  if (!configuredEmail || !configuredPassword) {
    return res.status(500).json({ success: false, error: 'Server authentication is not configured.' });
  }

  if (hash(email) !== hash(configuredEmail) || hash(password) !== hash(configuredPassword)) {
    return res.status(401).json({ success: false, error: 'Invalid email or password.' });
  }

  const token = crypto.randomBytes(32).toString('hex');
  sessions.set(token, { createdAt: Date.now(), expiresAt: Date.now() + SESSION_TTL_MS });

  res.cookie('voxora_session', token, {
    httpOnly: true,
    sameSite: 'lax',
    secure: process.env.NODE_ENV === 'production',
    maxAge: SESSION_TTL_MS,
    path: '/'
  });

  return res.json({ success: true });
});

/* =========================================================
   LOGOUT
========================================================= */

app.post('/api/auth/logout', (req, res) => {
  const token = req.cookies.voxora_session;
  if (token) sessions.delete(token);

  res.clearCookie('voxora_session', {
    httpOnly: true, sameSite: 'lax',
    secure: process.env.NODE_ENV === 'production', path: '/'
  });

  res.json({ success: true });
});

/* =========================================================
   GET ALL CLIENTS
========================================================= */

app.get('/api/instant-clients', requireAuth, async (req, res) => {
  if (!requireConfig(res)) return;

  try {
    const { data, error } = await supabase
      .from('instant_clients')
      .select('*')
      .order('created_at', { ascending: false });

    if (error) return res.status(500).json({ success: false, error: 'Failed to read clients.', details: error.message });
    return res.json({ success: true, clients: data || [] });
  } catch (err) {
    return res.status(500).json({ success: false, error: 'Failed to read clients.', details: err?.message || String(err) });
  }
});

/* =========================================================
   GET SINGLE CLIENT
========================================================= */

app.get('/api/instant-clients/:clientId', requireAuth, async (req, res) => {
  if (!requireConfig(res)) return;

  const clientId = String(req.params.clientId || '').trim();
  if (!clientId) return res.status(400).json({ success: false, error: 'Client ID is required.' });
  if (!isValidUUID(clientId)) return res.status(400).json({ success: false, error: 'Invalid client ID. A database UUID is required.' });

  try {
    const { data, error } = await supabase
      .from('instant_clients')
      .select('*')
      .eq(column.id, clientId)
      .maybeSingle();

    if (error) return res.status(500).json({ success: false, error: 'Failed to read client.', details: error.message });
    if (!data)  return res.status(404).json({ success: false, error: 'Client not found.' });
    return res.json({ success: true, client: data });
  } catch (err) {
    return res.status(500).json({ success: false, error: 'Failed to read client.', details: err?.message || String(err) });
  }
});

/* =========================================================
   CREATE CLIENT
========================================================= */

app.post('/api/instant-clients', requireAuth, async (req, res) => {
  if (!requireConfig(res)) return;

  const body = req.body || {};

  const clientName =
    typeof body.client_name === 'string'
      ? body.client_name.trim()
      : '';

  const agentId =
    typeof body.agent_id === 'string'
      ? body.agent_id.trim()
      : String(body.agent_id || '').trim();

  const fromNumberId =
    typeof body.from_number_id === 'string'
      ? body.from_number_id.trim()
      : String(body.from_number_id || '').trim();

  const source =
    typeof body.source === 'string' && body.source.trim()
      ? body.source.trim()
      : 'Website Form';

  const integrationToken =
    typeof body.integration_token === 'string' &&
    body.integration_token.trim()
      ? body.integration_token.trim()
      : 'il_' + crypto.randomBytes(10).toString('hex');

  if (!clientName || !agentId || !fromNumberId) {
    return res.status(400).json({
      success: false,
      error:
        'client_name, agent_id, and from_number_id are required.'
    });
  }

  try {
    /* -------------------------------------------------------
       1. CREATE CLIENT
    ------------------------------------------------------- */

    const insert = {
      [column.name]: clientName,
      [column.agent]: agentId,
      [column.fromNumber]: fromNumberId,
      [column.source]: source,
      [column.integrationToken]: integrationToken,
      [column.isActive]: true,
      updated_at: new Date().toISOString()
    };

    const {
      data: client,
      error: clientError
    } = await supabase
      .from('instant_clients')
      .insert(insert)
      .select('*')
      .single();

    if (clientError) {
      console.error('SUPABASE CLIENT INSERT ERROR:', clientError);

      return res.status(500).json({
        success: false,
        error: 'Supabase client insert failed.',
        details: clientError.message,
        code: clientError.code || null,
        hint: clientError.hint || null
      });
    }

    /* -------------------------------------------------------
       2. CREATE LINKED INTEGRATION
    ------------------------------------------------------- */

    const {
      data: integration,
      error: integrationError
    } = await supabase
      .from('instant_integrations')
      .insert({
        client_id: client.id,
        integration_token: integrationToken,
        integration_name: `${clientName} Instant Lead`,
        is_active: true
      })
      .select('*')
      .single();

    if (integrationError) {
      console.error(
        'SUPABASE INTEGRATION INSERT ERROR:',
        integrationError
      );

      /*
       * IMPORTANT:
       * If the integration cannot be created, remove the
       * client we just created so we don't leave an orphan
       * client without an integration.
       */
      await supabase
        .from('instant_clients')
        .delete()
        .eq('id', client.id);

      return res.status(500).json({
        success: false,
        error: 'Failed to create client integration.',
        details: integrationError.message,
        code: integrationError.code || null,
        hint: integrationError.hint || null
      });
    }

    /* -------------------------------------------------------
       3. RETURN BOTH RECORDS
    ------------------------------------------------------- */

    return res.status(201).json({
      success: true,
      client,
      integration
    });

  } catch (err) {
    console.error('CLIENT CREATE EXCEPTION:', err);

    return res.status(500).json({
      success: false,
      error: 'Backend exception.',
      details: err?.message || String(err)
    });
  }
});
/* =========================================================
   UPDATE CLIENT
========================================================= */

app.put('/api/instant-clients/:clientId', requireAuth, async (req, res) => {
  if (!requireConfig(res)) return;

  const clientId = String(req.params.clientId || '').trim();
  if (!clientId)         return res.status(400).json({ success: false, error: 'Client ID is required.' });
  if (!isValidUUID(clientId)) return res.status(400).json({ success: false, error: 'Invalid client ID. The client must use its Supabase UUID.' });

  const body = req.body || {};

  // Accept agent_id and from_number_id as plain strings (text columns).
  // Also tolerate the legacy omnidimension_* field names the frontend may send.
  const clientName   = typeof body.client_name === 'string' ? body.client_name.trim() : '';
  const agentId      = String(body.agent_id ?? body.omnidimension_agent_id ?? '').trim();
  const fromNumberId = String(body.from_number_id ?? body.omnidimension_from_number_id ?? '').trim();
  const source       = typeof body.source === 'string' ? body.source.trim() : null;

  if (!clientName || !agentId || !fromNumberId) {
    return res.status(400).json({
      success: false,
      error: 'client_name, agent_id, and from_number_id are required.'
    });
  }

  try {
    // Verify the client exists first.
    const { data: existingClient, error: existingError } = await supabase
      .from('instant_clients')
      .select('id')
      .eq(column.id, clientId)
      .maybeSingle();

    if (existingError) return res.status(500).json({ success: false, error: 'Failed to find client before update.', details: existingError.message });
    if (!existingClient) return res.status(404).json({ success: false, error: 'Client not found.' });

    const update = {
      [column.name]:       clientName,
      [column.agent]:      agentId,        // text, no conversion
      [column.fromNumber]: fromNumberId,   // text, no conversion
      updated_at: new Date().toISOString()
    };
    if (source !== null) update[column.source] = source;

    const { error: updateError } = await supabase
      .from('instant_clients')
      .update(update)
      .eq(column.id, clientId);

    if (updateError) {
      console.error('SUPABASE UPDATE ERROR:', updateError);
      return res.status(500).json({
        success: false,
        error: 'Supabase update failed.',
        details: updateError.message,
        code: updateError.code || null,
        hint: updateError.hint || null,
        details_from_supabase: updateError.details || null
      });
    }

    // Read the updated row back.
    const { data, error: readError } = await supabase
      .from('instant_clients')
      .select('*')
      .eq(column.id, clientId)
      .maybeSingle();

    if (readError) return res.status(500).json({ success: false, error: 'Client updated, but failed to read the updated client.', details: readError.message });
    if (!data)     return res.status(404).json({ success: false, error: 'Client not found after update.' });

    return res.json({ success: true, client: data });
  } catch (err) {
    console.error('CLIENT UPDATE EXCEPTION:', err);
    return res.status(500).json({ success: false, error: 'Backend exception.', details: err?.message || String(err) });
  }
});

/* =========================================================
   DELETE CLIENT
========================================================= */

app.delete('/api/instant-clients/:clientId', requireAuth, async (req, res) => {
  if (!requireConfig(res)) return;

  const clientId = String(req.params.clientId || '').trim();
  if (!clientId)         return res.status(400).json({ success: false, error: 'Client ID is required.' });
  if (!isValidUUID(clientId)) return res.status(400).json({ success: false, error: 'Invalid client ID. The client must use its Supabase UUID.' });

  try {
    const { data: existingClient, error: existingError } = await supabase
      .from('instant_clients')
      .select('id, client_name')
      .eq(column.id, clientId)
      .maybeSingle();

    if (existingError) return res.status(500).json({ success: false, error: 'Failed to find client before delete.', details: existingError.message });
    if (!existingClient) return res.status(404).json({ success: false, error: 'Client not found.' });

    const { error: deleteError } = await supabase
      .from('instant_clients')
      .delete()
      .eq(column.id, clientId);

    if (deleteError) {
      console.error('SUPABASE DELETE ERROR:', deleteError);
      return res.status(500).json({
        success: false,
        error: 'Supabase delete failed.',
        details: deleteError.message,
        code: deleteError.code || null,
        hint: deleteError.hint || null
      });
    }

    return res.json({ success: true, deleted_id: clientId, deleted_client_name: existingClient.client_name || null });
  } catch (err) {
    console.error('CLIENT DELETE EXCEPTION:', err);
    return res.status(500).json({ success: false, error: 'Backend exception.', details: err?.message || String(err) });
  }
});

/* =========================================================
   GET ALL INSTANT LEADS
========================================================= */

app.get('/api/instant-leads', requireAuth, async (req, res) => {
  if (!requireConfig(res)) return;

  try {
    const {
      data: leads,
      error: leadsError
    } = await supabase
      .from('instant_leads')
      .select('*')
      .order('created_at', {
        ascending: false
      });

    if (leadsError) {
      console.error('GET INSTANT LEADS ERROR:', leadsError);

      return res.status(500).json({
        success: false,
        error: 'Failed to read instant leads.',
        details: leadsError.message
      });
    }

    const {
      data: clients,
      error: clientsError
    } = await supabase
      .from('instant_clients')
      .select('id, client_name, source');

    if (clientsError) {
      console.error('GET INSTANT LEAD CLIENTS ERROR:', clientsError);

      return res.status(500).json({
        success: false,
        error: 'Failed to read client information.',
        details: clientsError.message
      });
    }

    const clientMap = {};
    (clients || []).forEach(client => {
      clientMap[String(client.id)] = client;
    });

    const enrichedLeads = (leads || []).map(lead => {
      const client = clientMap[String(lead.client_id)] || null;

      return {
        ...lead,
        client_name: client?.client_name || 'Unknown Client',
        source: client?.source || 'Website Form'
      };
    });

    return res.json({
      success: true,
      leads: enrichedLeads
    });

  } catch (err) {
    console.error('GET INSTANT LEADS EXCEPTION:', err);

    return res.status(500).json({
      success: false,
      error: 'Backend exception.',
      details: err?.message || String(err)
    });
  }
});

/* =========================================================
   GET ALL INSTANT LEADS
========================================================= */

app.get('/api/instant-leads', requireAuth, async (req, res) => {
  if (!requireConfig(res)) return;

  try {
    const { data: leads, error: leadsError } = await supabase
      .from('instant_leads')
      .select('*')
      .order('created_at', { ascending: false });

    if (leadsError) {
      console.error('GET INSTANT LEADS ERROR:', leadsError);

      return res.status(500).json({
        success: false,
        error: 'Failed to load instant leads.',
        details: leadsError.message
      });
    }

    const { data: clients, error: clientsError } = await supabase
      .from('instant_clients')
      .select('id, client_name, source');

    if (clientsError) {
      console.error('GET INSTANT LEAD CLIENTS ERROR:', clientsError);

      return res.status(500).json({
        success: false,
        error: 'Failed to load client information.',
        details: clientsError.message
      });
    }

    const clientMap = {};

    (clients || []).forEach(client => {
      clientMap[String(client.id)] = client;
    });

    const enrichedLeads = (leads || []).map(lead => {
      const client = clientMap[String(lead.client_id)];

      return {
        ...lead,
        client_name: client?.client_name || 'Unknown Client',
        source: client?.source || 'Website Form'
      };
    });

    return res.json({
      success: true,
      leads: enrichedLeads
    });

  } catch (error) {
    console.error('GET INSTANT LEADS EXCEPTION:', error);

    return res.status(500).json({
      success: false,
      error: 'Backend exception.',
      details: error?.message || String(error)
    });
  }
});

/* =========================================================
   PUBLIC INSTANT LEAD INGESTION + OMNIDIMENSION DISPATCH
========================================================= */

app.post('/instant-lead/:token', async (req, res) => {
  if (!requireConfig(res)) return;

  const token = String(req.params.token || '').trim();

  if (!token) {
    return res.status(400).json({
      success: false,
      error: 'Integration token is required.'
    });
  }

  const formData =
    req.body && typeof req.body === 'object'
      ? req.body
      : {};

  const phone = String(
    formData.phone ??
    formData.phone_number ??
    formData.mobile ??
    formData.mobile_number ??
    ''
  ).trim();

  const customerName = String(
    formData.customer_name ??
    formData.name ??
    ''
  ).trim();

  if (!phone) {
    return res.status(400).json({
      success: false,
      error: 'Customer phone number is required.'
    });
  }

  try {
    /* -------------------------------------------------------
       1. FIND INTEGRATION
    ------------------------------------------------------- */

    const {
      data: integration,
      error: integrationError
    } = await supabase
      .from('instant_integrations')
      .select('*')
      .eq('integration_token', token)
      .eq('is_active', true)
      .maybeSingle();

    if (integrationError) {
      console.error(
        'INSTANT LEAD INTEGRATION LOOKUP ERROR:',
        integrationError
      );

      return res.status(500).json({
        success: false,
        error: 'Failed to find integration.',
        details: integrationError.message
      });
    }

    if (!integration) {
      return res.status(404).json({
        success: false,
        error: 'Invalid or inactive integration token.'
      });
    }

    /* -------------------------------------------------------
       2. FIND CLIENT
    ------------------------------------------------------- */

    const {
      data: client,
      error: clientError
    } = await supabase
      .from('instant_clients')
      .select('*')
      .eq('id', integration.client_id)
      .maybeSingle();

    if (clientError) {
      console.error(
        'INSTANT LEAD CLIENT LOOKUP ERROR:',
        clientError
      );

      return res.status(500).json({
        success: false,
        error: 'Failed to find client.',
        details: clientError.message
      });
    }

    if (!client) {
      return res.status(404).json({
        success: false,
        error:
          'Client associated with this integration was not found.'
      });
    }

    /* -------------------------------------------------------
       3. PRESERVE ALL FORM DATA
    ------------------------------------------------------- */

    const rawFormData = { ...formData };

    const customData = {
      ...formData
    };

    /* -------------------------------------------------------
       4. CREATE LEAD
    ------------------------------------------------------- */

    const {
      data: lead,
      error: leadError
    } = await supabase
      .from('instant_leads')
      .insert({
        client_id: client.id,
        integration_id: integration.id,
        customer_name: customerName || null,
        phone,
        custom_data: customData,
        raw_form_data: rawFormData,
        call_status: 'pending'
      })
      .select('*')
      .single();

    if (leadError) {
      console.error(
        'INSTANT LEAD INSERT ERROR:',
        leadError
      );

      return res.status(500).json({
        success: false,
        error: 'Failed to save lead.',
        details: leadError.message,
        code: leadError.code || null,
        hint: leadError.hint || null
      });
    }

    /* -------------------------------------------------------
       5. BUILD DYNAMIC CALL CONTEXT
    ------------------------------------------------------- */

    const callContext = {
      ...customData
    };

    /* -------------------------------------------------------
       6. READ CLIENT OMNIDIMENSION IDS
    ------------------------------------------------------- */

    const rawAgentId =
      client.agent_id ??
      client.omnidimension_agent_id ??
      '';

    const rawFromNumberId =
      client.from_number_id ??
      client.omnidimension_from_number_id ??
      '';

    const agentIdText = String(
      rawAgentId ?? ''
    ).trim();

    const fromNumberIdText = String(
      rawFromNumberId ?? ''
    ).trim();

    const agentId =
      /^\d+$/.test(agentIdText)
        ? Number(agentIdText)
        : NaN;

    const fromNumberId =
      /^\d+$/.test(fromNumberIdText)
        ? Number(fromNumberIdText)
        : NaN;

    /* -------------------------------------------------------
       7. CHECK OMNIDIMENSION CONFIGURATION
    ------------------------------------------------------- */

    if (
      !Number.isSafeInteger(agentId) ||
      !Number.isSafeInteger(fromNumberId)
    ) {
      const pendingReason =
        !Number.isSafeInteger(agentId)
          ? 'OmniDimension agent_id is not configured as a valid numeric ID.'
          : 'OmniDimension from_number_id is not configured as a valid numeric ID.';

      await supabase
        .from('instant_leads')
        .update({
          call_status: 'pending',
          error_message: pendingReason,
          updated_at: new Date().toISOString()
        })
        .eq('id', lead.id);

      return res.status(201).json({
        success: true,
        lead_id: lead.id,
        client_id: client.id,
        client_name: client.client_name,
        integration_id: integration.id,
        call_status: 'pending',
        dispatch: 'waiting_for_omnidimension_configuration'
      });
    }

    /* -------------------------------------------------------
       8. CHECK API KEY
    ------------------------------------------------------- */

    const omniApiKey =
      String(
        process.env.OMNIDIM_API_KEY || ''
      ).trim();

    if (!omniApiKey) {
      const errorMessage =
        'OMNIDIM_API_KEY is not configured.';

      await supabase
        .from('instant_leads')
        .update({
          call_status: 'pending',
          error_message: errorMessage,
          updated_at: new Date().toISOString()
        })
        .eq('id', lead.id);

      return res.status(201).json({
        success: true,
        lead_id: lead.id,
        client_id: client.id,
        client_name: client.client_name,
        integration_id: integration.id,
        call_status: 'pending',
        dispatch: 'waiting_for_api_key'
      });
    }

    /* -------------------------------------------------------
       9. MARK DISPATCHING
    ------------------------------------------------------- */

    await supabase
      .from('instant_leads')
      .update({
        call_status: 'dispatching',
        error_message: null,
        updated_at: new Date().toISOString()
      })
      .eq('id', lead.id);

    /* -------------------------------------------------------
       10. DISPATCH OMNIDIMENSION CALL
    ------------------------------------------------------- */

    const dispatchPayload = {
      agent_id: agentId,
      to_number: phone,
      from_number_id: fromNumberId,
      call_context: callContext,
      metadata: {
        voxora_lead_id: lead.id,
        client_id: client.id,
        integration_id: integration.id,
        integration_token: token,
        source: client.source || 'Website Form'
      }
    };

    console.log(
      'OMNIDIMENSION DISPATCH REQUEST:',
      {
        agent_id: agentId,
        from_number_id: fromNumberId,
        to_number: phone,
        lead_id: lead.id
      }
    );

    const omniResponse = await fetch(
      'https://backend.omnidim.io/api/v1/calls/dispatch',
      {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${omniApiKey}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(dispatchPayload)
      }
    );

    const omniResult =
      await omniResponse
        .json()
        .catch(() => ({}));

    console.log(
      'OMNIDIMENSION DISPATCH RESPONSE:',
      omniResponse.status,
      omniResult
    );

    /* -------------------------------------------------------
       11. HANDLE DISPATCH FAILURE
    ------------------------------------------------------- */

    if (
      !omniResponse.ok ||
      !omniResult.success
    ) {
      const errorMessage =
        omniResult.error_description ||
        omniResult.error ||
        omniResult.message ||
        `OmniDimension dispatch failed with HTTP ${omniResponse.status}.`;

      await supabase
        .from('instant_leads')
        .update({
          call_status: 'failed',
          error_message: errorMessage,
          updated_at: new Date().toISOString()
        })
        .eq('id', lead.id);

      return res.status(201).json({
        success: true,
        lead_id: lead.id,
        client_id: client.id,
        client_name: client.client_name,
        integration_id: integration.id,
        call_status: 'failed',
        error: errorMessage
      });
    }

    /* -------------------------------------------------------
       12. SAVE DISPATCH RESULT
    ------------------------------------------------------- */

    const requestId =
      omniResult.requestId ??
      omniResult.request_id ??
      null;

    const callId =
      omniResult.callId ??
      omniResult.call_id ??
      null;

    await supabase
      .from('instant_leads')
      .update({
        call_status: 'dispatched',
        omnidim_request_id:
          requestId !== null
            ? String(requestId)
            : null,
        omnidim_call_id:
          callId !== null
            ? String(callId)
            : null,
        error_message: null,
        updated_at: new Date().toISOString()
      })
      .eq('id', lead.id);

    /* -------------------------------------------------------
       13. SUCCESS RESPONSE
    ------------------------------------------------------- */

    return res.status(201).json({
      success: true,
      lead_id: lead.id,
      client_id: client.id,
      client_name: client.client_name,
      integration_id: integration.id,
      call_status: 'dispatched',
      omnidim_request_id: requestId,
      omnidim_call_id: callId
    });

  } catch (err) {
    console.error(
      'INSTANT LEAD ERROR:',
      err
    );

    return res.status(500).json({
      success: false,
      error: 'Instant Lead processing failed.',
      details: err?.message || String(err)
    });
  }
});

/* =========================================================
   SERVE FRONTEND
========================================================= */

app.use(express.static(path.join(__dirname, '..')));

/* =========================================================
   START SERVER
========================================================= */

app.listen(port, () => {
  console.log(`Voxora Instant Leads API listening on http://localhost:${port}`);
});
